apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product-service
  name: product-service
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: product-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product-service
    spec:
      containers:
      - image: kawsikan/product-service:v1
        name: product-service
        resources: {}
status: {}