apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-05-19T14:18:23Z"
  labels:
    app: product-service
  name: product-service
  namespace: default
  resourceVersion: "5515"
  uid: 10d1644b-eea4-47a3-a768-0131c63d8dbb
spec:
  clusterIP: 10.64.7.205
  clusterIPs:
  - 10.64.7.205
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31124
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: product-service
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}